import type { Regions } from "@prisma/client";

interface Realm {
  name: string;
  slug: string;
}

export const realms: Record<Regions, Realm[]> = {
  us: [
    { name: "Gurubashi", slug: "gurubashi" },
    { name: "Skywall", slug: "skywall" },
    { name: "Dalaran", slug: "dalaran" },
    { name: "Garona", slug: "garona" },
    { name: "Thunderlord", slug: "thunderlord" },
    { name: "Dunemaul", slug: "dunemaul" },
    { name: "Azjol-Nerub", slug: "azjolnerub" },
    { name: "Firetree", slug: "firetree" },
    { name: "Runetotem", slug: "runetotem" },
    { name: "Grizzly Hills", slug: "grizzly-hills" },
    { name: "Galakrond", slug: "galakrond" },
    { name: "Dawnbringer", slug: "dawnbringer" },
    { name: "Draenor", slug: "draenor" },
    { name: "Sisters of Elune", slug: "sisters-of-elune" },
    { name: "Cenarion Circle", slug: "cenarion-circle" },
    { name: "Aggramar", slug: "aggramar" },
    { name: "Drak'Tharon", slug: "draktharon" },
    { name: "Ravencrest", slug: "ravencrest" },
    { name: "Windrunner", slug: "windrunner" },
    { name: "Scarlet Crusade", slug: "scarlet-crusade" },
    { name: "Stormreaver", slug: "stormreaver" },
    { name: "Elune", slug: "elune" },
    { name: "Shattered Hand", slug: "shattered-hand" },
    { name: "Bleeding Hollow", slug: "bleeding-hollow" },
    { name: "Trollbane", slug: "trollbane" },
    { name: "Winterhoof", slug: "winterhoof" },
    { name: "Maiev", slug: "maiev" },
    { name: "Muradin", slug: "muradin" },
    { name: "Vek'nilash", slug: "veknilash" },
    { name: "Sen'jin", slug: "senjin" },
    { name: "Skullcrusher", slug: "skullcrusher" },
    { name: "Argent Dawn", slug: "argent-dawn" },
    { name: "Destromath", slug: "destromath" },
    { name: "Gorgonnash", slug: "gorgonnash" },
    { name: "Dethecus", slug: "dethecus" },
    { name: "Bonechewer", slug: "bonechewer" },
    { name: "Dragonmaw", slug: "dragonmaw" },
    { name: "Silvermoon", slug: "silvermoon" },
    { name: "Terenas", slug: "terenas" },
    { name: "Gorefiend", slug: "gorefiend" },
    { name: "Lightning's Blade", slug: "lightnings-blade" },
    { name: "Eonar", slug: "eonar" },
    { name: "Kargath", slug: "kargath" },
    { name: "Llane", slug: "llane" },
    { name: "Earthen Ring", slug: "earthen-ring" },
    { name: "Laughing Skull", slug: "laughing-skull" },
    { name: "Burning Legion", slug: "burning-legion" },
    { name: "Malygos", slug: "malygos" },
    { name: "Thunderhorn", slug: "thunderhorn" },
    { name: "Dragonblight", slug: "dragonblight" },
    { name: "Uldum", slug: "uldum" },
    { name: "Hellscream", slug: "hellscream" },
    { name: "Kilrogg", slug: "kilrogg" },
    { name: "Spinebreaker", slug: "spinebreaker" },
    { name: "Eitrigg", slug: "eitrigg" },
    { name: "Nathrezim", slug: "nathrezim" },
    { name: "Feathermoon", slug: "feathermoon" },
    { name: "Bloodscalp", slug: "bloodscalp" },
    { name: "Rivendare", slug: "rivendare" },
    { name: "Nordrassil", slug: "nordrassil" },
    { name: "Cairne", slug: "cairne" },
    { name: "Shandris", slug: "shandris" },
    { name: "Moon Guard", slug: "moon-guard" },
    { name: "Nazgrel", slug: "nazgrel" },
    { name: "Hydraxis", slug: "hydraxis" },
    { name: "Lightbringer", slug: "lightbringer" },
    { name: "Uther", slug: "uther" },
    { name: "Proudmoore", slug: "proudmoore" },
    { name: "Cenarius", slug: "cenarius" },
    { name: "Blackrock", slug: "blackrock" },
    { name: "Silver Hand", slug: "silver-hand" },
    { name: "Doomhammer", slug: "doomhammer" },
    { name: "Icecrown", slug: "icecrown" },
    { name: "Kel'Thuzad", slug: "kelthuzad" },
    { name: "Frostmane", slug: "frostmane" },
    { name: "Madoran", slug: "madoran" },
    { name: "Azuremyst", slug: "azuremyst" },
    { name: "Auchindoun", slug: "auchindoun" },
    { name: "Coilfang", slug: "coilfang" },
    { name: "Shattered Halls", slug: "shattered-halls" },
    { name: "Blood Furnace", slug: "blood-furnace" },
    { name: "The Underbog", slug: "the-underbog" },
    { name: "Terokkar", slug: "terokkar" },
    { name: "Blade's Edge", slug: "blades-edge" },
    { name: "Exodar", slug: "exodar" },
    { name: "Area 52", slug: "area-52" },
    { name: "Zangarmarsh", slug: "zangarmarsh" },
    { name: "Fizzcrank", slug: "fizzcrank" },
    { name: "Mannoroth", slug: "mannoroth" },
    { name: "Nazjatar", slug: "nazjatar" },
    { name: "Malfurion", slug: "malfurion" },
    { name: "Aegwynn", slug: "aegwynn" },
    { name: "Akama", slug: "akama" },
    { name: "Emerald Dream", slug: "emerald-dream" },
    { name: "Smolderthorn", slug: "smolderthorn" },
    { name: "Blackhand", slug: "blackhand" },
    { name: "Whisperwind", slug: "whisperwind" },
    { name: "Archimonde", slug: "archimonde" },
    { name: "Stormrage", slug: "stormrage" },
    { name: "Medivh", slug: "medivh" },
    { name: "Durotan", slug: "durotan" },
    { name: "Bloodhoof", slug: "bloodhoof" },
    { name: "Khadgar", slug: "khadgar" },
    { name: "Rexxar", slug: "rexxar" },
    { name: "The Forgotten Coast", slug: "the-forgotten-coast" },
    { name: "Thorium Brotherhood", slug: "thorium-brotherhood" },
    { name: "Fenris", slug: "fenris" },
    { name: "Anub'arak", slug: "anubarak" },
    { name: "Blackwater Raiders", slug: "blackwater-raiders" },
    { name: "Vashj", slug: "vashj" },
    { name: "Korialstrasz", slug: "korialstrasz" },
    { name: "Darrowmere", slug: "darrowmere" },
    { name: "Shu'halo", slug: "shuhalo" },
    { name: "Arathor", slug: "arathor" },
    { name: "Staghelm", slug: "staghelm" },
    { name: "Eldre'Thalas", slug: "eldrethalas" },
    { name: "Dentarg", slug: "dentarg" },
    { name: "Demon Soul", slug: "demon-soul" },
    { name: "Spirestone", slug: "spirestone" },
    { name: "Hyjal", slug: "hyjal" },
    { name: "Lethon", slug: "lethon" },
    { name: "Blackwing Lair", slug: "blackwing-lair" },
    { name: "Arygos", slug: "arygos" },
    { name: "Duskwood", slug: "duskwood" },
    { name: "Illidan", slug: "illidan" },
    { name: "Lothar", slug: "lothar" },
    { name: "Sargeras", slug: "sargeras" },
    { name: "Azgalor", slug: "azgalor" },
    { name: "Magtheridon", slug: "magtheridon" },
    { name: "Shadowmoon", slug: "shadowmoon" },
    { name: "Drakkari", slug: "drakkari" },
    { name: "Ragnaros", slug: "ragnaros" },
    { name: "Shadow Council", slug: "shadow-council" },
    { name: "Cho'gall", slug: "chogall" },
    { name: "Gul'dan", slug: "guldan" },
    { name: "Kael'thas", slug: "kaelthas" },
    { name: "Alexstrasza", slug: "alexstrasza" },
    { name: "Kirin Tor", slug: "kirin-tor" },
    { name: "Balnazzar", slug: "balnazzar" },
    { name: "Drak'thul", slug: "drakthul" },
    { name: "Garithos", slug: "garithos" },
    { name: "Hakkar", slug: "hakkar" },
    { name: "Khaz Modan", slug: "khaz-modan" },
    { name: "Mug'thol", slug: "mugthol" },
    { name: "Kul Tiras", slug: "kul-tiras" },
    { name: "Malorne", slug: "malorne" },
    { name: "Echo Isles", slug: "echo-isles" },
    { name: "Zul'jin", slug: "zuljin" },
    { name: "Zuluhed", slug: "zuluhed" },
    { name: "Steamwheedle Cartel", slug: "steamwheedle-cartel" },
    { name: "Norgannon", slug: "norgannon" },
    { name: "Thrall", slug: "thrall" },
    { name: "Maelstrom", slug: "maelstrom" },
    { name: "Twisting Nether", slug: "twisting-nether" },
    { name: "Kalecgos", slug: "kalecgos" },
    { name: "Ursin", slug: "ursin" },
    { name: "Dark Iron", slug: "dark-iron" },
    { name: "Wildhammer", slug: "wildhammer" },
    { name: "Wyrmrest Accord", slug: "wyrmrest-accord" },
    { name: "Farstriders", slug: "farstriders" },
    { name: "Borean Tundra", slug: "borean-tundra" },
    { name: "Quel'dorei", slug: "queldorei" },
    { name: "Garrosh", slug: "garrosh" },
    { name: "Mok'Nathal", slug: "moknathal" },
    { name: "Nesingwary", slug: "nesingwary" },
    { name: "Drenden", slug: "drenden" },
    { name: "Azshara", slug: "azshara" },
    { name: "Agamaggan", slug: "agamaggan" },
    { name: "Lightninghoof", slug: "lightninghoof" },
    { name: "Baelgun", slug: "baelgun" },
    { name: "Anetheron", slug: "anetheron" },
    { name: "Turalyon", slug: "turalyon" },
    { name: "Haomarush", slug: "haomarush" },
    { name: "Ysondre", slug: "ysondre" },
    { name: "Ysera", slug: "ysera" },
    { name: "Andorhal", slug: "andorhal" },
    { name: "Executus", slug: "executus" },
    { name: "Black Dragonflight", slug: "black-dragonflight" },
    { name: "Altar of Storms", slug: "altar-of-storms" },
    { name: "Uldaman", slug: "uldaman" },
    { name: "Aerie Peak", slug: "aerie-peak" },
    { name: "Onyxia", slug: "onyxia" },
    { name: "Gnomeregan", slug: "gnomeregan" },
    { name: "The Venture Co", slug: "the-venture-co" },
    { name: "Sentinels", slug: "sentinels" },
    { name: "Jaedenar", slug: "jaedenar" },
    { name: "Tanaris", slug: "tanaris" },
    { name: "Alterac Mountains", slug: "alterac-mountains" },
    { name: "Undermine", slug: "undermine" },
    { name: "Tichondrius", slug: "tichondrius" },
    { name: "Bladefist", slug: "bladefist" },
    { name: "The Scryers", slug: "the-scryers" },
    { name: "Burning Blade", slug: "burning-blade" },
    { name: "Suramar", slug: "suramar" },
    { name: "Tortheldrin", slug: "tortheldrin" },
    { name: "Ner'zhul", slug: "nerzhul" },
    { name: "Alleria", slug: "alleria" },
    { name: "Deathwing", slug: "deathwing" },
    { name: "Arthas", slug: "arthas" },
    { name: "Draka", slug: "draka" },
    { name: "Velen", slug: "velen" },
    { name: "Frostwolf", slug: "frostwolf" },
    { name: "Misha", slug: "misha" },
    { name: "Moonrunner", slug: "moonrunner" },
    { name: "Ghostlands", slug: "ghostlands" },
    { name: "Eredar", slug: "eredar" },
    { name: "Korgath", slug: "korgath" },
    { name: "Detheroc", slug: "detheroc" },
    { name: "Ravenholdt", slug: "ravenholdt" },
    { name: "Gallywix", slug: "gallywix" },
    { name: "Crushridge", slug: "crushridge" },
    { name: "Daggerspine", slug: "daggerspine" },
    { name: "Stormscale", slug: "stormscale" },
    { name: "Boulderfist", slug: "boulderfist" },
    { name: "Stonemaul", slug: "stonemaul" },
    { name: "Greymane", slug: "greymane" },
    { name: "Kil'jaeden", slug: "kiljaeden" },
    { name: "Perenolde", slug: "perenolde" },
    { name: "Shadowsong", slug: "shadowsong" },
    { name: "Mal'Ganis", slug: "malganis" },
    { name: "Darkspear", slug: "darkspear" },
    { name: "Bronzebeard", slug: "bronzebeard" },
    { name: "Gilneas", slug: "gilneas" },
    { name: "Chromaggus", slug: "chromaggus" },
    { name: "Antonidas", slug: "antonidas" },
    { name: "Warsong", slug: "warsong" },
    { name: "Quel'Thalas", slug: "quelthalas" },
    { name: "Dalvengyr", slug: "dalvengyr" },
    { name: "Scilla", slug: "scilla" },
    { name: "Anvilmar", slug: "anvilmar" },
    { name: "Goldrinn", slug: "goldrinn" },
    { name: "Nemesis", slug: "nemesis" },
    { name: "Azralon", slug: "azralon" },
    { name: "Tol Barad", slug: "tol-barad" },
    { name: "Dreadmaul", slug: "dreadmaul" },
    { name: "Caelestrasz", slug: "caelestrasz" },
    { name: "Nagrand", slug: "nagrand" },
    { name: "Aman'Thul", slug: "amanthul" },
    { name: "Barthilas", slug: "barthilas" },
    { name: "Thaurissan", slug: "thaurissan" },
    { name: "Dath'Remar", slug: "dathremar" },
    { name: "Frostmourne", slug: "frostmourne" },
    { name: "Khaz'goroth", slug: "khazgoroth" },
    { name: "Jubei'Thos", slug: "jubeithos" },
    { name: "Gundrak", slug: "gundrak" },
    { name: "Saurfang", slug: "saurfang" },
  ],
  eu: [
    { name: "Khadgar", slug: "khadgar" },
    { name: "Chromaggus", slug: "chromaggus" },
    { name: "Dentarg", slug: "dentarg" },
    { name: "La Croisade écarlate", slug: "la-croisade-écarlate" },
    { name: "Runetotem", slug: "runetotem" },
    { name: "Shadowsong", slug: "shadowsong" },
    { name: "Silvermoon", slug: "silvermoon" },
    { name: "Sunstrider", slug: "sunstrider" },
    { name: "Executus", slug: "executus" },
    { name: "Mazrigos", slug: "mazrigos" },
    { name: "Karazhan", slug: "karazhan" },
    { name: "Auchindoun", slug: "auchindoun" },
    { name: "Shattered Halls", slug: "shattered-halls" },
    { name: "Гордунни", slug: "gordunni" },
    { name: "Свежеватель Душ", slug: "soulflayer" },
    { name: "Страж Смерти", slug: "deathguard" },
    { name: "Sporeggar", slug: "sporeggar" },
    { name: "Nethersturm", slug: "nethersturm" },
    { name: "Shattrath", slug: "shattrath" },
    { name: "Подземье", slug: "deepholm" },
    { name: "Echsenkessel", slug: "echsenkessel" },
    { name: "Blutkessel", slug: "blutkessel" },
    { name: "Галакронд", slug: "galakrond" },
    { name: "Разувий", slug: "razuvious" },
    { name: "Ткач Смерти", slug: "deathweaver" },
    { name: "Terenas", slug: "terenas" },
    { name: "Thunderhorn", slug: "thunderhorn" },
    { name: "Turalyon", slug: "turalyon" },
    { name: "Ravencrest", slug: "ravencrest" },
    { name: "Shattered Hand", slug: "shattered-hand" },
    { name: "Spinebreaker", slug: "spinebreaker" },
    { name: "Stormscale", slug: "stormscale" },
    { name: "Earthen Ring", slug: "earthen-ring" },
    { name: "Alexstrasza", slug: "alexstrasza" },
    { name: "Alleria", slug: "alleria" },
    { name: "Antonidas", slug: "antonidas" },
    { name: "Blackhand", slug: "blackhand" },
    { name: "Gilneas", slug: "gilneas" },
    { name: "Kargath", slug: "kargath" },
    { name: "Khaz'goroth", slug: "khazgoroth" },
    { name: "Madmortem", slug: "madmortem" },
    { name: "Zuluhed", slug: "zuluhed" },
    { name: "Nozdormu", slug: "nozdormu" },
    { name: "Perenolde", slug: "perenolde" },
    { name: "Aegwynn", slug: "aegwynn" },
    { name: "Dun Morogh", slug: "dun-morogh" },
    { name: "Thrall", slug: "thrall" },
    { name: "Theradras", slug: "theradras" },
    { name: "Genjuros", slug: "genjuros" },
    { name: "Balnazzar", slug: "balnazzar" },
    { name: "Wrathbringer", slug: "wrathbringer" },
    { name: "Talnivarr", slug: "talnivarr" },
    { name: "Emeriss", slug: "emeriss" },
    { name: "Drak'thul", slug: "drakthul" },
    { name: "Ahn'Qiraj", slug: "ahnqiraj" },
    { name: "Ysera", slug: "ysera" },
    { name: "Malygos", slug: "malygos" },
    { name: "Anetheron", slug: "anetheron" },
    { name: "Nazjatar", slug: "nazjatar" },
    { name: "Tichondrius", slug: "tichondrius" },
    { name: "Steamwheedle Cartel", slug: "steamwheedle-cartel" },
    { name: "Die ewige Wacht", slug: "die-ewige-wacht" },
    { name: "Die Todeskrallen", slug: "die-todeskrallen" },
    { name: "Die Arguswacht", slug: "die-arguswacht" },
    { name: "Uldaman", slug: "uldaman" },
    { name: "Confrérie du Thorium", slug: "confrérie-du-thorium" },
    { name: "Dragonblight", slug: "dragonblight" },
    { name: "Tarren Mill", slug: "tarren-mill" },
    { name: "C'Thun", slug: "cthun" },
    { name: "Alonsus", slug: "alonsus" },
    { name: "Blade's Edge", slug: "blades-edge" },
    { name: "Doomhammer", slug: "doomhammer" },
    { name: "Twilight's Hammer", slug: "twilights-hammer" },
    { name: "Daggerspine", slug: "daggerspine" },
    { name: "Sargeras", slug: "sargeras" },
    { name: "Emerald Dream", slug: "emerald-dream" },
    { name: "Quel'Thalas", slug: "quelthalas" },
    { name: "Bloodscalp", slug: "bloodscalp" },
    { name: "Burning Blade", slug: "burning-blade" },
    { name: "Crushridge", slug: "crushridge" },
    { name: "Dragonmaw", slug: "dragonmaw" },
    { name: "Dunemaul", slug: "dunemaul" },
    { name: "Dethecus", slug: "dethecus" },
    { name: "Durotan", slug: "durotan" },
    { name: "Aggramar", slug: "aggramar" },
    { name: "Arathor", slug: "arathor" },
    { name: "Azjol-Nerub", slug: "azjolnerub" },
    { name: "Draenor", slug: "draenor" },
    { name: "Vol'jin", slug: "voljin" },
    { name: "Arak-arahm", slug: "arakarahm" },
    { name: "Zenedar", slug: "zenedar" },
    { name: "Agamaggan", slug: "agamaggan" },
    { name: "Bladefist", slug: "bladefist" },
    { name: "Culte de la Rive noire", slug: "culte-de-la-rive-noire" },
    { name: "Argent Dawn", slug: "argent-dawn" },
    { name: "Onyxia", slug: "onyxia" },
    { name: "Nefarian", slug: "nefarian" },
    { name: "Das Syndikat", slug: "das-syndikat" },
    { name: "Laughing Skull", slug: "laughing-skull" },
    { name: "Neptulon", slug: "neptulon" },
    { name: "Twisting Nether", slug: "twisting-nether" },
    { name: "The Maelstrom", slug: "the-maelstrom" },
    { name: "Bloodfeather", slug: "bloodfeather" },
    { name: "Frostwhisper", slug: "frostwhisper" },
    { name: "Kor'gall", slug: "korgall" },
    { name: "Defias Brotherhood", slug: "defias-brotherhood" },
    { name: "Rashgarroth", slug: "rashgarroth" },
    { name: "Les Sentinelles", slug: "les-sentinelles" },
    { name: "Suramar", slug: "suramar" },
    { name: "Garrosh", slug: "garrosh" },
    { name: "Arygos", slug: "arygos" },
    { name: "Teldrassil", slug: "teldrassil" },
    { name: "Lordaeron", slug: "lordaeron" },
    { name: "Aggra (Português)", slug: "aggra-português" },
    { name: "Terokkar", slug: "terokkar" },
    { name: "Baelgun", slug: "baelgun" },
    { name: "Cho'gall", slug: "chogall" },
    { name: "Nordrassil", slug: "nordrassil" },
    { name: "Sylvanas", slug: "sylvanas" },
    { name: "Drek'Thar", slug: "drekthar" },
    { name: "Ghostlands", slug: "ghostlands" },
    { name: "The Sha'tar", slug: "the-shatar" },
    { name: "Chants éternels", slug: "chants-éternels" },
    { name: "Marécage de Zangar", slug: "marécage-de-zangar" },
    { name: "Naxxramas", slug: "naxxramas" },
    { name: "Arthas", slug: "arthas" },
    { name: "Azshara", slug: "azshara" },
    { name: "Blackmoore", slug: "blackmoore" },
    { name: "Destromath", slug: "destromath" },
    { name: "Eredar", slug: "eredar" },
    { name: "Frostwolf", slug: "frostwolf" },
    { name: "Kil'jaeden", slug: "kiljaeden" },
    { name: "Mal'Ganis", slug: "malganis" },
    { name: "Zirkel des Cenarius", slug: "zirkel-des-cenarius" },
    { name: "Vashj", slug: "vashj" },
    { name: "Hyjal", slug: "hyjal" },
    { name: "Ulduar", slug: "ulduar" },
    { name: "Ревущий фьорд", slug: "howling-fjord" },
    { name: "Al'Akir", slug: "alakir" },
    { name: "Stormreaver", slug: "stormreaver" },
    { name: "Magtheridon", slug: "magtheridon" },
    { name: "Lightning's Blade", slug: "lightnings-blade" },
    { name: "Kirin Tor", slug: "kirin-tor" },
    { name: "Archimonde", slug: "archimonde" },
    { name: "Elune", slug: "elune" },
    { name: "Chamber of Aspects", slug: "chamber-of-aspects" },
    { name: "Ravenholdt", slug: "ravenholdt" },
    { name: "Pozzo dell'Eternità", slug: "pozzo-delleternità" },
    { name: "Eonar", slug: "eonar" },
    { name: "Vek'nilash", slug: "veknilash" },
    { name: "Frostmane", slug: "frostmane" },
    { name: "Bloodhoof", slug: "bloodhoof" },
    { name: "Kael'thas", slug: "kaelthas" },
    { name: "Haomarush", slug: "haomarush" },
    { name: "Khaz Modan", slug: "khaz-modan" },
    { name: "Varimathras", slug: "varimathras" },
    { name: "Hakkar", slug: "hakkar" },
    { name: "Blackrock", slug: "blackrock" },
    { name: "Kel'Thuzad", slug: "kelthuzad" },
    { name: "Mannoroth", slug: "mannoroth" },
    { name: "Proudmoore", slug: "proudmoore" },
    { name: "Garona", slug: "garona" },
    { name: "Darkmoon Faire", slug: "darkmoon-faire" },
    { name: "Vek'lor", slug: "veklor" },
    { name: "Mug'thol", slug: "mugthol" },
    { name: "Taerar", slug: "taerar" },
    { name: "Dalvengyr", slug: "dalvengyr" },
    { name: "Rajaxx", slug: "rajaxx" },
    { name: "Malorne", slug: "malorne" },
    { name: "Der abyssische Rat", slug: "der-abyssische-rat" },
    { name: "Der Mithrilorden", slug: "der-mithrilorden" },
    { name: "Ambossar", slug: "ambossar" },
    { name: "Krasus", slug: "krasus" },
    { name: "Arathi", slug: "arathi" },
    { name: "Ysondre", slug: "ysondre" },
    { name: "Eldre'Thalas", slug: "eldrethalas" },
    { name: "Kilrogg", slug: "kilrogg" },
    { name: "Wildhammer", slug: "wildhammer" },
    { name: "Saurfang", slug: "saurfang" },
    { name: "Nemesis", slug: "nemesis" },
    { name: "Дракономор", slug: "fordragon" },
    { name: "Борейская тундра", slug: "borean-tundra" },
    { name: "Les Clairvoyants", slug: "les-clairvoyants" },
    { name: "Skullcrusher", slug: "skullcrusher" },
    { name: "Lothar", slug: "lothar" },
    { name: "Sinstralis", slug: "sinstralis" },
    { name: "Terrordar", slug: "terrordar" },
    { name: "Scarshield Legion", slug: "scarshield-legion" },
    { name: "Kul Tiras", slug: "kul-tiras" },
    { name: "Stormrage", slug: "stormrage" },
    { name: "Ner'zhul", slug: "nerzhul" },
    { name: "Dun Modr", slug: "dun-modr" },
    { name: "Zul'jin", slug: "zuljin" },
    { name: "Uldum", slug: "uldum" },
    { name: "Sanguino", slug: "sanguino" },
    { name: "Shen'dralar", slug: "shendralar" },
    { name: "Tyrande", slug: "tyrande" },
    { name: "Exodar", slug: "exodar" },
    { name: "Los Errantes", slug: "los-errantes" },
    { name: "Lightbringer", slug: "lightbringer" },
    { name: "Darkspear", slug: "darkspear" },
    { name: "Burning Steppes", slug: "burning-steppes" },
    { name: "Bronze Dragonflight", slug: "bronze-dragonflight" },
    { name: "Anachronos", slug: "anachronos" },
    { name: "Spirestone", slug: "colinas-pardas" },
    { name: "Un'Goro", slug: "ungoro" },
    { name: "Illidan", slug: "illidan" },
    { name: "Rexxar", slug: "rexxar" },
    { name: "Festung der Stürme", slug: "festung-der-stürme" },
    { name: "Gul'dan", slug: "guldan" },
    { name: "Aszune", slug: "aszune" },
    { name: "Aerie Peak", slug: "aerie-peak" },
    { name: "Xavius", slug: "xavius" },
    { name: "Throk'Feroth", slug: "throkferoth" },
    { name: "Minahonda", slug: "minahonda" },
    { name: "Tirion", slug: "tirion" },
    { name: "Sen'jin", slug: "senjin" },
    { name: "Trollbane", slug: "trollbane" },
    { name: "Aman'Thul", slug: "amanthul" },
    { name: "Bronzebeard", slug: "bronzebeard" },
    { name: "Die Aldor", slug: "die-aldor" },
    { name: "Temple noir", slug: "temple-noir" },
    { name: "Вечная Песня", slug: "eversong" },
    { name: "Термоштепсель", slug: "thermaplugg" },
    { name: "Гром", slug: "grom" },
    { name: "Голдринн", slug: "goldrinn" },
    { name: "Черный Шрам", slug: "blackscar" },
    { name: "Forscherliga", slug: "forscherliga" },
    { name: "Eitrigg", slug: "eitrigg" },
    { name: "Todeswache", slug: "todeswache" },
    { name: "Dalaran", slug: "dalaran" },
    { name: "Frostmourne", slug: "frostmourne" },
    { name: "Malfurion", slug: "malfurion" },
    { name: "Krag'jin", slug: "kragjin" },
    { name: "Gorgonnash", slug: "gorgonnash" },
    { name: "Burning Legion", slug: "burning-legion" },
    { name: "Azuremyst", slug: "azuremyst" },
    { name: "Anub'arak", slug: "anubarak" },
    { name: "Nera'thor", slug: "nerathor" },
    { name: "Kult der Verdammten", slug: "kult-der-verdammten" },
    { name: "Der Rat von Dalaran", slug: "der-rat-von-dalaran" },
    { name: "Hellscream", slug: "hellscream" },
    { name: "Ragnaros", slug: "ragnaros" },
    { name: "Darksorrow", slug: "darksorrow" },
    { name: "The Venture Co", slug: "the-venture-co" },
    { name: "Grim Batol", slug: "grim-batol" },
    { name: "Jaedenar", slug: "jaedenar" },
    { name: "Kazzak", slug: "kazzak" },
    { name: "Moonglade", slug: "moonglade" },
    { name: "Conseil des Ombres", slug: "conseil-des-ombres" },
    { name: "Nathrezim", slug: "nathrezim" },
    { name: "Das Konsortium", slug: "das-konsortium" },
    { name: "Boulderfist", slug: "boulderfist" },
    { name: "Deathwing", slug: "deathwing" },
    { name: "Area 52", slug: "area-52" },
    { name: "Die Nachtwache", slug: "die-nachtwache" },
    { name: "Пиратская Бухта", slug: "booty-bay" },
    { name: "Король-лич", slug: "lich-king" },
    { name: "Hellfire", slug: "hellfire" },
    { name: "Outland", slug: "outland" },
    { name: "Седогрив", slug: "greymane" },
    { name: "Medivh", slug: "medivh" },
    { name: "Die Silberne Hand", slug: "die-silberne-hand" },
    { name: "Nagrand", slug: "nagrand" },
    { name: "Азурегос", slug: "azuregos" },
    { name: "Ясеневый лес", slug: "ashenvale" },
    { name: "Norgannon", slug: "norgannon" },
  ],
  kr: [
    { name: "아즈샤라", slug: "azshara" },
    { name: "불타는 군단", slug: "burning-legion" },
    { name: "굴단", slug: "guldan" },
    { name: "말퓨리온", slug: "malfurion" },
    { name: "달라란", slug: "dalaran" },
    { name: "듀로탄", slug: "durotan" },
    { name: "노르간논", slug: "norgannon" },
    { name: "가로나", slug: "garona" },
    { name: "윈드러너", slug: "windrunner" },
    { name: "헬스크림", slug: "hellscream" },
    { name: "알렉스트라자", slug: "alexstrasza" },
    { name: "렉사르", slug: "rexxar" },
    { name: "하이잘", slug: "hyjal" },
    { name: "데스윙", slug: "deathwing" },
    { name: "세나리우스", slug: "cenarius" },
    { name: "스톰레이지", slug: "stormrage" },
    { name: "줄진", slug: "zuljin" },
    { name: "와일드해머", slug: "wildhammer" },
  ],
  tw: [
    { name: "血之谷", slug: "bleeding-hollow" },
    { name: "寒冰皇冠", slug: "icecrown" },
    { name: "冰風崗哨", slug: "chillwind-point" },
    { name: "世界之樹", slug: "world-tree" },
    { name: "暗影之月", slug: "shadowmoon" },
    { name: "尖石", slug: "spirestone" },
    { name: "雷鱗", slug: "stormscale" },
    { name: "亞雷戈斯", slug: "arygos" },
    { name: "憤怒使者", slug: "wrathbringer" },
    { name: "阿薩斯", slug: "arthas" },
    { name: "狂熱之刃", slug: "zealot-blade" },
    { name: "聖光之願", slug: "lights-hope" },
    { name: "屠魔山谷", slug: "demon-fall-canyon" },
    { name: "巨龍之喉", slug: "dragonmaw" },
    { name: "日落沼澤", slug: "sundown-marsh" },
    { name: "冰霜之刺", slug: "frostmane" },
    { name: "地獄吼", slug: "hellscream" },
    { name: "天空之牆", slug: "skywall" },
    { name: "米奈希爾", slug: "menethil" },
    { name: "語風", slug: "whisperwind" },
    { name: "夜空之歌", slug: "nightsong" },
    { name: "水晶之刺", slug: "crystalpine-stinger" },
    { name: "銀翼要塞", slug: "silverwing-hold" },
    { name: "眾星之子", slug: "queldorei" },
    { name: "雲蛟衛", slug: "order-of-the-cloud-serpent" },
    { name: "克羅之刃", slug: "krol-blade" },
    { name: "老馬布蘭契", slug: "old-blanchy" },
  ],
};
